name: "test"

on:
  workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

    - name: "🔖 Test release body"
      uses: softprops/action-gh-release@v1
      with:
        name: "test"
        tag_name: "test"
        body: "This\nis\na\ntest\n."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
